import type { Product } from "@/types/product";

export const placeholderProducts: Product[] = [
  {
    id: "sp-001",
    handle: "velocity-cream-runner",
    title: "Velocity Cream Runner",
    vendor: "Sneak-Peak Atelier",
    price: "R 3 999",
    compareAtPrice: "R 4 699",
    badge: "New drop",
    description:
      "A sculpted premium runner with layered suede, breathable mesh, and a clean cream palette made for daily rotation.",
    fitNote: "True to size with a secure midfoot fit.",
    productCode: "SP-VCR-01",
    features: ["Responsive foam cushioning", "Breathable mesh panels", "High-abrasion rubber outsole"],
    materials: ["Suede and engineered mesh upper", "Textile lining", "Rubber outsole"],
    images: [
      {
        src: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
        alt: "Red premium sneaker side profile",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/velocity-8",
        title: "UK 7 / Cream",
        size: "UK 7",
        colorway: "Cream",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/velocity-9",
        title: "UK 8 / Cream",
        size: "UK 8",
        colorway: "Cream",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/velocity-10",
        title: "UK 9 / Cream",
        size: "UK 9",
        colorway: "Cream",
        availableForSale: true,
      },
    ],
    tags: ["Runner", "New Releases"],
  },
  {
    id: "sp-002",
    handle: "court-noir-low",
    title: "Court Noir Low",
    vendor: "Sneak-Peak Select",
    price: "R 3 399",
    badge: "Limited",
    description:
      "Low-cut court heritage with tumbled leather, padded lining, and a matte black finish.",
    fitNote: "Fits slightly narrow. Size up if you prefer more room.",
    productCode: "SP-CNL-02",
    features: ["Padded low-cut collar", "Cupsole construction", "Pivot-point traction"],
    materials: ["Tumbled leather upper", "Textile lining", "Rubber cupsole"],
    images: [
      {
        src: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=1200&q=80",
        alt: "Black and white sneaker on dark floor",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/noir-8",
        title: "UK 7 / Noir",
        size: "UK 7",
        colorway: "Noir",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/noir-9",
        title: "UK 8 / Noir",
        size: "UK 8",
        colorway: "Noir",
        availableForSale: false,
      },
    ],
    tags: ["Court", "Limited"],
  },
  {
    id: "sp-003",
    handle: "summit-knit-high",
    title: "Summit Knit High",
    vendor: "Sneak-Peak Lab",
    price: "R 4 399",
    description:
      "A high-collar knit sneaker with a lightweight sole unit and tonal technical overlays.",
    fitNote: "Sock-like fit. Choose your usual size.",
    productCode: "SP-SKH-03",
    features: ["Supportive knit collar", "Lightweight foam platform", "Tonal bonded overlays"],
    materials: ["Engineered knit upper", "Textile lining", "Rubber traction pods"],
    images: [
      {
        src: "https://images.unsplash.com/photo-1605348532760-6753d2c43329?auto=format&fit=crop&w=1200&q=80",
        alt: "High top sneaker on minimal background",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/summit-9",
        title: "UK 8 / Stone",
        size: "UK 8",
        colorway: "Stone",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/summit-10",
        title: "UK 9 / Stone",
        size: "UK 9",
        colorway: "Stone",
        availableForSale: false,
      },
    ],
    tags: ["High Top", "Performance"],
  },
  {
    id: "sp-004",
    handle: "archive-gum-trainer",
    title: "Archive Gum Trainer",
    vendor: "Sneak-Peak Vault",
    price: "R 2 999",
    badge: "Restock",
    description:
      "A relaxed trainer with archival paneling, gum rubber traction, and easy all-season styling.",
    fitNote: "Relaxed everyday fit with a roomy toe box.",
    productCode: "SP-AGT-04",
    features: ["Archive-inspired panelling", "Cushioned footbed", "Gum traction outsole"],
    materials: ["Mixed textile and synthetic upper", "Textile lining", "Gum rubber outsole"],
    images: [
      {
        src: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=1200&q=80",
        alt: "Colorful trainer sneaker pair",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/archive-8",
        title: "UK 7 / Gum",
        size: "UK 7",
        colorway: "Gum",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/archive-11",
        title: "UK 10 / Gum",
        size: "UK 10",
        colorway: "Gum",
        availableForSale: true,
      },
    ],
    tags: ["Trainer", "Restocks"],
  },
  {
    id: "sp-005",
    handle: "studio-white-low",
    title: "Studio White Low",
    vendor: "Sneak-Peak Essentials",
    price: "R 3 199",
    badge: "Essential",
    description:
      "A clean white low-top with soft leather construction, understated paneling, and an easy profile built for everyday wear.",
    fitNote: "True to size. Breaks in naturally with wear.",
    productCode: "SP-SWL-05",
    features: ["Minimal court profile", "Perforated ventilation", "Cushioned collar"],
    materials: ["Soft leather upper", "Textile lining", "Rubber cupsole"],
    images: [
      {
        src: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1200&q=80",
        alt: "White low-top sneaker on a neutral backdrop",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/studio-8",
        title: "UK 7 / White",
        size: "UK 7",
        colorway: "White",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/studio-9",
        title: "UK 8 / White",
        size: "UK 8",
        colorway: "White",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/studio-10",
        title: "UK 9 / White",
        size: "UK 9",
        colorway: "White",
        availableForSale: true,
      },
    ],
    tags: ["Court", "New Releases"],
  },
  {
    id: "sp-006",
    handle: "ember-street-runner",
    title: "Ember Street Runner",
    vendor: "Sneak-Peak Select",
    price: "R 3 599",
    badge: "New drop",
    description:
      "A streamlined street runner with layered technical panels, responsive cushioning, and a warm ember colorway that carries the whole look.",
    fitNote: "Performance fit. Size up for casual wear.",
    productCode: "SP-ESR-06",
    features: ["Responsive cushioning", "Layered support cage", "Road-ready rubber grip"],
    materials: ["Mesh and synthetic upper", "Textile lining", "Rubber outsole"],
    images: [
      {
        src: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=1200&q=80",
        alt: "Sneaker pair angled on an orange backdrop",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/ember-8",
        title: "UK 7 / Ember",
        size: "UK 7",
        colorway: "Ember",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/ember-9",
        title: "UK 8 / Ember",
        size: "UK 8",
        colorway: "Ember",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/ember-11",
        title: "UK 10 / Ember",
        size: "UK 10",
        colorway: "Ember",
        availableForSale: true,
      },
    ],
    tags: ["Runner", "New Releases"],
  },
  {
    id: "sp-007",
    handle: "aero-blue-knit",
    title: "Aero Blue Knit",
    vendor: "Sneak-Peak Lab",
    price: "R 3 799",
    description:
      "Lightweight knit construction meets a cushioned performance sole in a cool blue palette designed for long days on the move.",
    fitNote: "Adaptive knit fit. Choose your usual size.",
    productCode: "SP-ABK-07",
    features: ["Flexible knit construction", "Cushioned performance sole", "Heel support clip"],
    materials: ["Engineered knit upper", "Textile lining", "Rubber outsole"],
    images: [
      {
        src: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=1200&q=80",
        alt: "Light knit sneakers arranged on a blue backdrop",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/aero-8",
        title: "UK 7 / Ice Blue",
        size: "UK 7",
        colorway: "Ice Blue",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/aero-9",
        title: "UK 8 / Ice Blue",
        size: "UK 8",
        colorway: "Ice Blue",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/aero-10",
        title: "UK 9 / Ice Blue",
        size: "UK 9",
        colorway: "Ice Blue",
        availableForSale: false,
      },
    ],
    tags: ["Runner", "Performance"],
  },
  {
    id: "sp-008",
    handle: "heritage-canvas-classic",
    title: "Heritage Canvas Classic",
    vendor: "Sneak-Peak Vault",
    price: "R 2 599",
    badge: "Restock",
    description:
      "A timeless canvas silhouette with a vulcanized sole, familiar proportions, and the kind of versatility that earns repeat wear.",
    fitNote: "Fits slightly large. Consider half a size down.",
    productCode: "SP-HCC-08",
    features: ["Timeless low profile", "Reinforced toe cap", "Vulcanised construction"],
    materials: ["Canvas upper", "Textile lining", "Vulcanised rubber outsole"],
    images: [
      {
        src: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=1200&q=80",
        alt: "Classic canvas sneaker against a white background",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/heritage-8",
        title: "UK 7 / Natural",
        size: "UK 7",
        colorway: "Natural",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/heritage-9",
        title: "UK 8 / Natural",
        size: "UK 8",
        colorway: "Natural",
        availableForSale: true,
      },
      {
        id: "gid://shopify/ProductVariant/heritage-10",
        title: "UK 9 / Natural",
        size: "UK 9",
        colorway: "Natural",
        availableForSale: true,
      },
    ],
    tags: ["Trainer", "Restocks"],
  },
];
